baseURL = 'https://example.org/'
title = 'My New Hugo Project'

defaultContentLanguage = 'en'

disableKinds = ['taxonomy', 'term', 'rss', 'sitemap']

[languages.en]
label = 'English'
weight = 1

[languages.ru]
label = 'Русский'
weight = 2

[params.accounts]
email = 'mailto:wpdevelopment11@gmail.com'
github = 'https://github.com/wpdevelopment11'
telegram = ''

[[languages.en.menus.main]]
name = 'Tutorials'
pageRef = '#tutorials'
weight = 10
[[languages.en.menus.main]]
name = 'Programming&nbsp;projects'
pageRef = '#programming_projects'
weight = 20
[[languages.en.menus.main]]
name = 'Contributions'
pageRef = '#contributions'
weight = 30
[[languages.en.menus.main]]
name = 'Training'
pageRef = '#training'
weight = 40
[[languages.en.menus.main]]
name = 'Contact'
pageRef = '#contact'
weight = 50

[[languages.ru.menus.main]]
name = 'Руководства'
pageRef = '#tutorials'
weight = 10
[[languages.ru.menus.main]]
name = 'Программирование'
pageRef = '#programming_projects'
weight = 20
[[languages.ru.menus.main]]
name = 'Вклад в другие проекты'
pageRef = '#contributions'
weight = 30
[[languages.ru.menus.main]]
name = 'Тренировки'
pageRef = '#training'
weight = 40
[[languages.ru.menus.main]]
name = 'Контакты'
pageRef = '#contact'
weight = 50
