[[tutorials]]
title = "Set up an Xray-core VLESS proxy to access blocked websites and apps"
url = "https://github.com/wpdevelopment11/xray-tutorial"
last_updated = 2026-09-11

[[tutorials]]
title = "Running Windows games on Linux using Wine and DXVK in a sandbox"
url = "https://community.hetzner.com/tutorials/running-windows-games-on-linux-using-wine-and-dxvk-in-a-sandbox"
source = "https://github.com/wpdevelopment11/community-content/blob/master/tutorials/running-windows-games-on-linux-using-wine-and-dxvk-in-a-sandbox/01.en.md"
last_updated = 2026-04-14

[[tutorials]]
title = "Obfuscating WireGuard using Wstunnel"
url = "https://community.hetzner.com/tutorials/obfuscating-wireguard-using-wstunnel"
source = "https://github.com/wpdevelopment11/community-content/blob/master/tutorials/obfuscating-wireguard-using-wstunnel/01.en.md"
last_updated = 2026-01-12

[[tutorials]]
title = "Encrypting your files in the cloud using securefs"
url = "https://community.hetzner.com/tutorials/encrypting-your-files-in-the-cloud-using-securefs"
source = "https://github.com/wpdevelopment11/community-content/blob/master/tutorials/encrypting-your-files-in-the-cloud-using-securefs/01.en.md"
last_updated = 2025-12-03

[[tutorials]]
title = "Run WordPress in a container using Docker Compose"
url = "https://community.hetzner.com/tutorials/run-wordpress-in-a-container-using-docker-compose"
source = "https://github.com/wpdevelopment11/community-content/blob/master/tutorials/run-wordpress-in-a-container-using-docker-compose/01.en.md"
last_updated = 2025-08-25

[[tutorials]]
title = "How to use FFmpeg for video editing"
url = "https://community.hetzner.com/tutorials/how-to-use-ffmpeg-for-video-editing"
source = "https://github.com/wpdevelopment11/community-content/blob/master/tutorials/how-to-use-ffmpeg-for-video-editing/01.en.md"
last_updated = 2025-05-28

[[tutorials]]
title = "Restrict access by an IP or password in nginx"
url = "https://community.hetzner.com/tutorials/restrict-access-by-ip-or-password-in-nginx"
source = "https://github.com/wpdevelopment11/community-content/blob/master/tutorials/restrict-access-by-ip-or-password-in-nginx/01.en.md"
last_updated = 2025-01-27

[[tutorials]]
title = "Installing and configuring WireGuard VPN on Ubuntu"
url = "https://community.hetzner.com/tutorials/install-and-configure-wireguard-vpn"
source = "https://github.com/wpdevelopment11/community-content/blob/master/tutorials/install-and-configure-wireguard-vpn/01.en.md"
last_updated = 2025-01-27

[[tutorials]]
title = "Analyze nginx access log using SQL"
url = "https://community.hetzner.com/tutorials/analyze-nginx-access-log-using-sql"
source = "https://github.com/wpdevelopment11/community-content/blob/master/tutorials/analyze-nginx-access-log-using-sql/01.en.md"
last_updated = 2024-08-19

[[tutorials]]
title = "Installing WordPress on Ubuntu"
url = "https://community.hetzner.com/tutorials/installing-wordpress-on-ubuntu"
source = "https://github.com/wpdevelopment11/community-content/blob/master/tutorials/installing-wordpress-on-ubuntu/01.en.md"
last_updated = 2023-12-11
